version: 1.0.{build}
image: Visual Studio 2017
configuration:
- Debug
- Release
platform:
- x86
- x64
- ARM
environment:
  PfxPassword:
    secure: t6Y2F3pUhBZUsOLZZwmo65o0lvYOn/70XyJvB2go+Mk=
before_build:
- cmd: nuget restore
- ps: $psw = ConvertTo-SecureString $env:PfxPassword -AsPlainText -Force
- ps: Import-PfxCertificate -FilePath .\Moonlight\Moonlight_TemporaryKey.pfx -CertStoreLocation cert:\CurrentUser\My -Password $psw
- ps: Import-PfxCertificate -FilePath .\Moonlight\Moonlight_TemporaryKey.pfx -CertStoreLocation cert:\CurrentUser\Root -Password $psw
build:
  parallel: true
  verbosity: minimal
